name: Selenium Tests

on:
  push:
    branches:
      - demosite

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up ChromeDriver
      run: |
        LATEST_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        curl -O https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Build and Run Selenium Tests
      run: |
        ./mvnw clean test -Dbrowser=chrome
